- scripts/npc/npc_abilities_custom.txt
- scripts/vscripts/bot/bot_item_data.lua
[b]游戏性更新 v1.21a[/b]
修正机器人出装。
[b]Gameplay update v1.21a[/b]
Repair bots netural items.
> v1.21a revert April Fools event

- game/scripts/vscripts/heroes/hero_yukari/yukari_moon_portal.lua
#388
#385
八云紫E对自己使用时固定禁锢时间
二段E冷却时间修复
> 八云紫E对自己使用时固定禁锢时间 & 二段E冷却时间修复

- game/resource/addon_english.txt
- game/resource/addon_schinese.txt
- game/scripts/npc/npc_abilities_custom.txt
- game/scripts/npc/npc_items_custom.txt
- game/scripts/vscripts/events.lua
- game/scripts/vscripts/items/item_hand_of_group.lua
- game/scripts/vscripts/util.lua
平衡点金手数值，修正描述
修正肉山钱袋数值显示，平衡数量
初次更新 加钱数值改保守点
> fix about gold

- game/resource/addon_english.txt
- game/resource/addon_schinese.txt
- game/scripts/npc/npc_abilities_override.txt
- game/scripts/npc/npc_items_custom.txt
- game/scripts/npc/npc_units_custom.txt
- game/scripts/vscripts/items/item_refresh_core.lua
- game/scripts/vscripts/lua_abilities/tinker_rearm_lua/tinker_rearm_lua.lua
[b]游戏性更新 v1.53[/b]
同步dota2 7.32d版本更新。
[b]Gameplay update v1.53[/b]
Update with dota2 7.32d path.
> v1.53 fix 7.32d

- game/scripts/npc/npc_abilities_override.txt
- game/scripts/npc/npc_items_custom.txt
- game/scripts/vscripts/bot/bot_item_data.lua
- game/scripts/vscripts/bot/bot_think_item_build.lua
- game/scripts/vscripts/items/item_abyssal_blade_v2.lua
- game/scripts/vscripts/items/item_excalibur.lua
- game/scripts/vscripts/items/item_heavens_halberd_v2.lua
[b]游戏性更新 v2.11f[/b]
优化自定义道具代码，缓解卡顿。
[b]Gameplay update v2.11f[/b]
Optimized the implementation of items may reduce lag.
> v2.11f fix lag, return items

- game/scripts/npc/npc_abilities_custom.txt
- game/scripts/npc/npc_abilities_override.txt
- game/scripts/npc/npc_items_custom.txt
- game/scripts/vscripts/events.lua
[b]游戏性更新 v2.24a[/b]
平衡性调整。
[b]Gameplay update v2.24a[/b]
Balance adjustment.
> v2.24a balance

- content/panorama/scripts/custom_game/game_mode.js
- game/scripts/npc/npc_items_override.txt
- game/scripts/vscripts/ai_game_mode.lua
- src/vscripts/ai/AI.ts
- src/vscripts/ai/action/action-attack.ts
- src/vscripts/ai/action/action-find.ts
- src/vscripts/ai/action/action-move.ts
- src/vscripts/ai/hero/hero-base.ts
- src/vscripts/ai/hero/hero-util.ts
- src/vscripts/ai/mode/FSA.ts
- src/vscripts/ai/mode/mode-attack.ts
- src/vscripts/ai/mode/mode-base.ts
- src/vscripts/ai/mode/mode-enum.ts
- src/vscripts/ai/mode/mode-laning.ts
- src/vscripts/ai/mode/mode-push.ts
- src/vscripts/ai/mode/mode-retreat.ts
- src/vscripts/ai/mode/mode-rune.ts
- src/vscripts/ai/team/team-strategy.ts
- src/vscripts/modules/event/event.ts
> Bot not rush tower

- game/resource/addon_english.txt
- game/resource/addon_schinese.txt
- game/scripts/npc/npc_items_custom.txt
- game/scripts/vscripts/bot/bot_item_data.lua
- game/scripts/vscripts/items/item_hand_of_group.lua
- src/vscripts/ai/action/action-ability.ts
- src/vscripts/ai/action/action-find.ts
- src/vscripts/ai/action/action-item.ts
- src/vscripts/ai/hero/hero-base.ts
- src/vscripts/modules/debug/Debug.ts
> Fix hand of group

- game/scripts/npc/npc_abilities_custom.txt
- game/scripts/npc/npc_abilities_override.txt
- game/scripts/npc/npc_heroes_custom.txt
- game/scripts/vscripts/heroes/hero_yukari/yukari_twin_trains.lua
- src/vscripts/ai/hero/hero-base.ts
- src/vscripts/ai/mode/mode-attack.ts
- src/vscripts/ai/mode/mode-laning.ts
- src/vscripts/ai/mode/mode-push.ts
- src/vscripts/ai/mode/mode-retreat.ts
- src/vscripts/modules/GameConfig.ts
- src/vscripts/modules/debug/debug-cmd.ts
> 被替换英雄的部分技能回归&一些英雄强度调整

- game/scripts/npc/npc_items_custom.txt
- game/scripts/npc/npc_items_modifier.txt
- game/scripts/vscripts/items/item_adi_king.lua
- game/scripts/vscripts/items/item_adi_king_plus.lua
> #819 improve aki king game freeze

- game/scripts/npc/npc_heroes_custom.txt
- game/scripts/vscripts/bot/bot_think_ability_use.lua
- game/scripts/vscripts/event/chat.lua
- src/vscripts/ai/AI.ts
- src/vscripts/ai/action/action-ability.ts
- src/vscripts/ai/action/action-find.ts
- src/vscripts/ai/hero/hero-base.ts
- src/vscripts/ai/hero/hero-lion.ts
- src/vscripts/ai/hero/hero-viper.ts
- src/vscripts/modules/debug/Debug.ts
- src/vscripts/modules/debug/debug-cmd.ts
- src/vscripts/modules/event/event-npc-spawned.ts
> #811 Impl lion, viper ability usage

- game/scripts/vscripts/event/bot_herolist.lua
> Change N6 hero list

- README.md
- game/scripts/npc/npc_items_custom.txt
- game/scripts/vscripts/items/item_dragon_ball.lua
- game/scripts/vscripts/util.lua
- src/vscripts/api/game.ts
- src/vscripts/modules/event/event-entity-killed.ts
> Fix dragon ball combination

- content/panorama/layout/custom_game/battlepass.xml
- content/panorama/scripts/custom_game/battlepass.js
- content/panorama/styles/custom_game/battlepass.css
- game/resource/addon_english.txt
- game/resource/addon_schinese.txt
- src/vscripts/api/player.ts
> Improve player panel UI

- game/resource/addon_english.txt
- game/resource/addon_schinese.txt
- game/scripts/npc/npc_items_custom.txt
- game/scripts/npc/npc_items_override.txt
- game/scripts/shops.txt
- game/scripts/vscripts/bot/bot_item_data.lua
- game/scripts/vscripts/bot/bot_think_ability_use.lua
[b]游戏性更新 v3.20b[/b]
平衡一些神器
[b]Gameplay update v3.20b[/b]
Fix Artifacts description and some balance.
> Balance artificial 2.0 and trans english

- .vscode/settings.json
- game/scripts/npc/npc_abilities_override.txt
- game/scripts/npc/npc_heroes_custom.txt
https://www.dota2.com/patches/7.36?l=schinese
> Fix dota2 7.36 hero abilities

- content/panorama/layout/custom_game/custom_loading_screen.xml
- content/panorama/scripts/custom_game/battlepass.js
- game/scripts/npc/npc_abilities_override.txt
- game/scripts/npc/npc_items_custom.txt
- src/vscripts/modules/GameConfig.ts
> Fix 7.36 axe culling blade bug

- .github/workflows/auto_create_develop_pr.yml
> fix auto pr

- game/scripts/npc/npc_abilities_override.txt
- game/scripts/npc/npc_units_custom.txt
> fix warlock golem scale 修正术士地狱火模型太大

- game/scripts/npc/npc_abilities_override.txt
- game/scripts/npc/npc_heroes_custom.txt
> fix snapfire 修正霹雳铁手 攻击力加成不生效

- game/scripts/npc/npc_items_custom.txt
> fix bloodthorn ultra passive bug

- game/scripts/npc/npc_items_custom.txt
- game/scripts/vscripts/bot/bot_think_item_build.lua
- src/vscripts/ai/hero/hero-util.ts
> 修正AI英雄在被哈斯卡A帐大招控的时候 却可以施法的问题

- .github/FUNDING.yml
- game/resource/addon_english.txt
- game/resource/addon_schinese.txt
> fix afdian domain

- game/resource/addon_schinese.txt
- game/scripts/npc/npc_items_custom.txt
- src/vscripts/api/game.ts
> fix sacred and vladmir

- game/scripts/npc/npc_abilities_override.txt
- src/vscripts/api/api_client.ts
- src/vscripts/api/game.ts
- src/vscripts/api/player.ts
> update api key

- game/resource/addon_english.txt
- game/resource/addon_schinese.txt
Greatly improved English localization, allowing for better readability for English-speaking/reading players.
> English localization.

- .github/dependabot.yml
- .github/workflows/auto_merge_develop_pr.yml
- .github/workflows/auto_merge_release_pr.yml
- .github/workflows/create_develop_pr.yml
- .github/workflows/create_release_pr.yml
> enable dependabot, improve workflow

- game/resource/addon_english.txt
- game/resource/addon_schinese.txt
- game/scripts/npc/npc_abilities_custom.txt
- game/scripts/npc/npc_abilities_override.txt
- game/scripts/npc/npc_items_custom.txt
- package-lock.json
- package.json
- tool/transAbilitySpeciaToAbilityValues.ts
> Fix item and ability AbilitySpecial to AbilityValues

- game/scripts/vscripts/items/item_hand_of_group.lua
- game/scripts/vscripts/items/item_royal_jelly_custom.lua
- game/scripts/vscripts/items/item_tome_of_agility.lua
- game/scripts/vscripts/items/item_tome_of_intelligence.lua
- game/scripts/vscripts/items/item_tome_of_luoshu.lua
- game/scripts/vscripts/items/item_tome_of_strength.lua
- src/vscripts/api/game.ts
> Fix SpendCharge param

- game/resource/addon_schinese.txt
- game/scripts/npc/npc_items_artifact.txt
- game/scripts/npc/npc_items_custom.txt
- game/scripts/npc/npc_items_override.txt
- game/scripts/shops.txt
- src/vscripts/modules/GameConfig.ts
> Fix item change in 7.37

- content/panorama/layout/custom_game/team_select/team_select.xml
- game/scripts/vscripts/events.lua
- src/vscripts/api/player.ts
- src/vscripts/modules/GameConfig.ts
- src/vscripts/modules/event/event-game-state-change.ts
- src/vscripts/modules/hero/hero-pick.ts
> 玩家数据偶尔加载漏人

- game/resource/addon_english.txt
- game/resource/addon_schinese.txt
- game/scripts/npc/npc_items_artifact.txt
- game/scripts/npc/npc_items_override.txt
- game/scripts/shops.txt
- src/vscripts/api/game.ts
- src/vscripts/modules/GameConfig.ts
> 德鲁伊小熊能无损卖光暗中立刷钱

- game/scripts/npc/npc_items_custom.txt
- src/vscripts/modules/debug/Debug.ts
> 电脑书放在备用格子不吃掉

- game/resource/addon_english.txt
- game/resource/addon_schinese.txt
- game/scripts/npc/npc_items_artifact.txt
- game/scripts/npc/npc_items_override.txt
- src/vscripts/modules/event/event-entity-killed.ts
> Fix light dark artifact

- game/scripts/npc/npc_abilities_override.txt
- game/scripts/npc/npc_heroes_custom.txt
> 修正luna大招的快捷键

- content/panorama/scripts/custom_game/game_mode.js
- game/scripts/npc/npc_heroes_custom.txt
- game/scripts/vscripts/bot/bot_item_data.lua
- game/scripts/vscripts/bot/bot_think_item_build.lua
- src/vscripts/api/game.ts
- src/vscripts/modules/GameConfig.ts
- src/vscripts/modules/debug/Debug.ts
- src/vscripts/modules/debug/debug-cmd.ts
> 修正电脑吃太多智力书导致魔抗超100%的问题

- game/scripts/vscripts/event/kill.lua
- src/vscripts/modules/event/custom-event.ts
- src/vscripts/modules/event/event-entity-killed.ts
- src/vscripts/modules/option.ts
> 修正复活时间异常的问题

- .github/workflows/ci.yml
> fix create develop workflow

- src/vscripts/modules/event/event-entity-killed.ts
> fix hero respawn time

- .github/workflows/create_release_pr.yml
- game/scripts/npc/npc_abilities_override.txt
- game/scripts/npc/npc_items_custom.txt
> 解决出门祭台送泉水的问题

- content/panorama/scripts/custom_game/game_mode.js
- game/scripts/npc/npc_abilities_custom.txt
- game/scripts/vscripts/heroes/hero_yukari/yukari01.lua
- game/scripts/vscripts/heroes/hero_yukari/yukari04.lua
> [BUG] 八云紫的A杖现在不能持续引导，直接就会过去，还会产生持续的噪音

- content/maps/changelog.md
> Fix Neutral Pull time

- game/resource/addon_english.txt
- game/resource/addon_schinese.txt
> 补充部分自定义技能英文描述缺失

- game/scripts/npc/herolist.txt
- game/scripts/npc/npc_abilities_override.txt
- src/vscripts/api/game.ts
Added the new hero, Kez!
-All of his abilities now have an extra level, and scale accordingly.
--Some aspects of him are stronger than in the base game. This is merely for testing purposes and will likely be readjusted after players have tried him out in this game mode.
> Kez update

- .vscode/extensions.json
- README.md
- package.json
- src/scripts/launch.js
> Improve dev launch and tstl setting

- .github/workflows/create_develop_pr.yml
- game/scripts/npc/npc_abilities_override.txt
> fix create develop pr

- game/scripts/npc/npc_abilities_override.txt
- game/scripts/npc/npc_items_override.txt
- game/scripts/npc/npc_units_custom.txt
> Update with dota2 7.37e

- README.md
- src/scripts/install.js
- src/scripts/launch.js
- src/vscripts/api/api-client.ts
> Refactor api

- package.json
- src/common/net_tables.d.ts
- src/panorama/tsconfig.json
- src/panorama/webpack.prod.js
> Fix net table setting

- content/panorama/scripts/custom_game/item_choice.js
- content/panorama/scripts/custom_game/utils.js
- game/scripts/custom_net_tables.txt
- src/common/dto/lottery-item.d.ts
- src/common/dto/lottery.d.ts
- src/common/events.d.ts
- src/common/net_tables.d.ts
- src/vscripts/modules/lottery/lottery.ts
> Refactor item lottery with nettable

- src/panorama/webpack.dev.js
> Watch less when dev

- game/scripts/custom_net_tables.txt
- src/common/dto/lottery-status.d.ts
- src/common/net_tables.d.ts
- src/vscripts/modules/debug/Debug.ts
- src/vscripts/modules/helper/net-table-helper.ts
- src/vscripts/modules/lottery/lottery.ts
> Impl pick refresh check

- src/panorama/react/hud_lottery/script.tsx
- src/vscripts/modules/debug/Debug.ts
- src/vscripts/modules/lottery/lottery-helper.ts
- src/vscripts/modules/lottery/lottery.ts
> Lottery exclude hero abilities UI auto close

- game/resource/addon_english.txt
- game/resource/addon_schinese.txt
- src/vscripts/api/game.ts
> Fourth anniversary

- content/panorama/layout/custom_game/point_info/point_info.css
- game/scripts/npc/npc_abilities_custom.txt
- game/scripts/vscripts/ai_game_mode.lua
- src/vscripts/modules/filter/gold-xp-filter.test.ts
- src/vscripts/modules/filter/gold-xp-filter.ts
> Balance n6

- game/scripts/npc/npc_abilities_custom.txt
- game/scripts/npc/npc_items_override.txt
- src/vscripts/api/game.ts
- src/vscripts/modules/lottery/lottery-abilities.ts
> 随机技能池添加更多法球/开关技能

- src/vscripts/api/analytics.ts
- src/vscripts/api/game.ts
- src/vscripts/modules/GameConfig.ts
- src/vscripts/modules/lottery/lottery-abilities.ts
- src/vscripts/modules/lottery/lottery.ts
> Send ability pick event

- game/scripts/npc/npc_abilities_override.txt
- src/vscripts/api/analytics.ts
- src/vscripts/modules/lottery/lottery.ts
> Send lottery_pick_item event

- game/scripts/npc/npc_abilities_override.txt
- game/scripts/npc/npc_items_custom.txt
- game/scripts/vscripts/ai_game_mode.lua
- game/scripts/vscripts/events.lua
- src/vscripts/modules/GameConfig.ts
- src/vscripts/modules/event/event-buyback.ts
- src/vscripts/modules/event/event-entity-killed.ts
- src/vscripts/modules/event/event.ts
> Refactor tab scoreboard. Remove lua is member

- content/panorama/layout/custom_game/custom_loading_screen.xml
- content/panorama/layout/custom_game/flyout_scoreboard/shared_scoreboard_updater.js
- content/panorama/scripts/custom_game/end_screen_2.js
- content/panorama/scripts/custom_game/game_mode.js
- game/resource/addon_english.txt
- game/resource/addon_schinese.txt
- game/scripts/custom_net_tables.txt
- game/scripts/kv/game_option.kv
- game/scripts/npc/npc_abilities_override.txt
- game/scripts/vscripts/ai_game_mode.lua
- game/scripts/vscripts/bot/bot_think_item_build.lua
- game/scripts/vscripts/event/js_event.lua
- src/common/events.d.ts
- src/common/net_tables.d.ts
- src/vscripts/modules/GameConfig.ts
- src/vscripts/modules/event/custom/loading-set-options.ts
- src/vscripts/modules/lottery/lottery.ts
- src/vscripts/modules/option.ts
> Refactor game option

- game/resource/addon_english.txt
- game/resource/addon_schinese.txt
- game/scripts/npc/npc_abilities_custom.txt
- src/vscripts/modules/event/game-end/game-end-helper.test.ts
- src/vscripts/modules/event/game-end/game-end-helper.ts
- src/vscripts/modules/filter/gold-xp-filter.test.ts
- src/vscripts/modules/filter/gold-xp-filter.ts
- src/vscripts/modules/helper/bot-power.ts
[b]游戏性更新 v4.05c[/b]
微调勇士积分的算法。
加强N6，N5添加机械救赎，一些平衡性改动。
[b]Gameplay update v4.05c[/b]
Slightly adjusted the Battle Points algorithm.
Strengthen N6, N5 add bot power, some balance.
> Fix points, kill gold balance, n5 bot power

- content/panorama/scripts/custom_game/game_mode.js
- game/scripts/vscripts/bot/bot_think_item_build.lua
- game/scripts/vscripts/event/kill.lua
[b]游戏性更新 v4.05d[/b]
修正多人联机时，自定义选项不生效的问题
略微削弱电脑。
[b]Gameplay update v4.05d[/b]
Fixed custom game options not working in multiplayer.
Slightly nerfed bots.
> Fix custom options. Balance nerf bot

- game/resource/addon_schinese.txt
- src/panorama/react/hud_lottery/components/ExpandButton.tsx
- src/panorama/react/hud_lottery/components/KeySettingButton.tsx
- src/panorama/react/hud_lottery/hotkey.ts
- src/panorama/utils/utils.ts
> UI show abitity hotkey

- game/resource/addon_english.txt
- game/resource/addon_schinese.txt
- game/scripts/npc/neutral_items.txt
- game/scripts/npc/npc_abilities_override.txt
- game/scripts/npc/npc_items_artifact.txt
- game/scripts/npc/npc_items_override.txt
- game/scripts/shops.txt
- src/vscripts/modules/lottery/lottery-abilities.ts
- src/vscripts/modules/lottery/lottery-items.ts
- src/vscripts/modules/lottery/lottery.ts
> Ability Item lottery increased to 4 out of 1

- game/scripts/npc/npc_abilities_override.txt
- game/scripts/npc/npc_items_artifact.txt
- src/vscripts/api/api-client.ts
- src/vscripts/modules/GameConfig.ts
- src/vscripts/modules/event/event-game-state-change.ts
- src/vscripts/modules/event/game-end/game-end-helper.test.ts
- src/vscripts/modules/event/game-end/game-end-helper.ts
- src/vscripts/modules/lottery/lottery-abilities.ts
> Fix minimap icon color

- src/vscripts/modules/event/event-game-state-change.ts
> Set Player color when game start

- game/scripts/npc/npc_abilities_custom.txt
- game/scripts/npc/npc_abilities_override.txt
- game/scripts/npc/npc_items_artifact.txt
- game/scripts/npc/npc_items_custom.txt
- game/scripts/npc/npc_items_override.txt
- game/scripts/vscripts/bot/bot_item_data.lua
- game/scripts/vscripts/bot/bot_think_item_build.lua
- game/scripts/vscripts/event/kill.lua
- src/vscripts/modules/helper/player-helper.ts
- src/vscripts/modules/lottery/lottery-abilities.ts
> Fix bug and balance

- game/scripts/npc/npc_abilities_override.txt
- game/scripts/npc/npc_heroes_custom.txt
- game/scripts/npc/npc_items_artifact.txt
- src/vscripts/modules/debug/Debug.ts
- src/vscripts/modules/debug/debug-cmd.ts
- src/vscripts/modules/lottery/lottery-abilities.ts
> Adjust lottery abilities

- game/scripts/npc/npc_units_creep.txt
> Fix creep bug

- game/scripts/npc/npc_abilities_override.txt
- game/scripts/npc/npc_heroes_custom.txt
- game/scripts/vscripts/bot/bot_think_item_build.lua
- game/scripts/vscripts/event/kill.lua
- src/vscripts/modules/lottery/lottery-abilities.ts
- src/vscripts/utils/precache.ts
> Improve lottery abilities, remove unused precache

- game/scripts/npc/neutral_items.txt
- game/scripts/npc/npc_items_override.txt
- src/vscripts/modules/GameConfig.ts
- src/vscripts/modules/lottery/lottery-abilities.ts
- src/vscripts/modules/lottery/lottery-items.ts
- src/vscripts/utils/precache.ts
> Adjust item lottery

- game/resource/addon_english.txt
- game/resource/addon_schinese.txt
- game/scripts/npc/npc_abilities_creep.txt
- game/scripts/npc/npc_abilities_custom.txt
- game/scripts/npc/npc_abilities_custom_new.txt
- game/scripts/npc/npc_abilities_override.txt
- game/scripts/npc/npc_items_artifact.txt
- game/scripts/vscripts/abilities/ogre_magi_multicast_lua.lua
- game/scripts/vscripts/util.lua
- src/vscripts/modules/GameConfig.ts
- src/vscripts/modules/lottery/lottery-abilities.ts
- src/vscripts/modules/lottery/lottery-items.ts
- src/vscripts/utils/precache.ts
> New ability multicast

- src/vscripts/modules/GameConfig.ts
- src/vscripts/modules/lottery/lottery-abilities.ts
- src/vscripts/utils/precache-data.ts
- src/vscripts/utils/precache.ts
> Fix ability mods

- content/panorama/scripts/custom_game/game_mode.js
- game/scripts/npc/npc_abilities_custom_new.txt
- game/scripts/vscripts/abilities/ogre_magi_multicast_lua.lua
- game/scripts/vscripts/bot/bot_item_data.lua
> Fixed multicast targeting to target multiple units in range

- game/resource/addon_english.txt
- game/resource/addon_schinese.txt
- game/scripts/npc/npc_abilities_custom_new.txt
- game/scripts/npc/npc_abilities_override.txt
- game/scripts/npc/npc_items_artifact.txt
- game/scripts/npc/npc_items_override.txt
- game/scripts/vscripts/abilities/ogre_magi_multicast_lua.lua
- game/scripts/vscripts/abilities/spectre_dispersion2.lua
- src/vscripts/modules/GameConfig.ts
> SetPreGameTime to 1min, dispersion2 shard

- game/scripts/npc/npc_abilities_override.txt
- game/scripts/npc/npc_items_override.txt
- game/scripts/npc/npc_units_creep.txt
- game/scripts/vscripts/bot/bot_item_data.lua
> Reduce line creep Bounty

- game/resource/addon_schinese.txt
- game/scripts/npc/npc_items_custom.txt
> Artifact Heaven's Halberd stats not working

- .vscode/extensions.json
- content/panorama/layout/custom_game/team_select/team_select.js
- game/resource/addon_english.txt
- game/resource/addon_schinese.txt
- game/scripts/npc/npc_abilities_override.txt
- game/scripts/npc/npc_heroes_custom.txt
- game/scripts/vscripts/abilities/ogre_magi_multicast_lua.lua
- src/vscripts/modules/event/game-end/game-end-point.test.ts
- src/vscripts/modules/event/game-end/game-end-point.ts
> Fix Skeleton King talent. Prevent multicast while hero is channeling

- src/panorama/react/hud_lottery/hotkey.ts
- src/vscripts/modules/GameConfig.ts
> Fixed hotkey display issues.

- src/panorama/react/hud_lottery/hotkey.ts
[b]游戏性更新 v4.19b[/b]
自定义改键实装在按下 Alt 键时对自己施法，切换自动施法的功能。
优化商店成列和物品图标。
[b]Gameplay update v4.19b[/b]
Custom hotkey implement self cast and toggle auto cast when Alt key is pressed.
Improve item icons shops.
> Custom hotkey self cast/toggle auto cast when Alt key is pressed.

- content/panorama/layout/custom_game/board/boards.css
- content/panorama/layout/custom_game/board/boards.js
- content/panorama/layout/custom_game/board/boards.xml
- game/scripts/custom_net_tables.txt
- src/common/net_tables.d.ts
- src/vscripts/api/api-client.ts
- src/vscripts/api/player.ts
- src/vscripts/api/ranking.ts
- src/vscripts/modules/event/event-game-state-change.ts
> Improve ranking UI

- .github/workflows/create_release_pr.yml
- .github/workflows/test.yml
- README.md
> Improve workflow

- src/vscripts/api/analytics/analytics.ts
- src/vscripts/modules/lottery/lottery.ts
> 移除lotter ability start GA4事件

- game/scripts/vscripts/bot/bot_item_data.lua
> Fix bot item build

- game/scripts/vscripts/items/item_tome_of_luoshu.lua
- src/vscripts/modules/lottery/lottery-abilities.ts
> Fix luoshu buff

- src/vscripts/modules/event/game-end/game-end-point.test.ts
- src/vscripts/modules/event/game-end/game-end-point.ts
- src/vscripts/modules/event/game-end/game-end.ts
> Afk detect

- src/vscripts/modules/event/game-end/game-end-point.test.ts
- src/vscripts/modules/event/game-end/game-end-point.ts
- src/vscripts/modules/event/game-end/game-end.ts
> improve end points afk

- content/maps/changelog.md
> Sync Dota7.38c map

- game/scripts/vscripts/ai_game_mode.lua
- game/scripts/vscripts/events.lua
- src/vscripts/modules/event/event-player-level-up.ts
> Adjust hero death exp more in early game, less in later game.

- game/scripts/npc/npc_abilities_override.txt
- game/scripts/npc/npc_heroes_custom.txt
- src/vscripts/ai/action/action-move.ts
- src/vscripts/modules/GameConfig.ts
- src/vscripts/modules/event/event-npc-spawned.ts
- src/vscripts/modules/event/game-end/game-end-point.test.ts
- src/vscripts/modules/event/game-end/game-end-point.ts
- src/vscripts/modules/hero/hero-pick.ts
> Enable BOT facet

- src/vscripts/api/analytics/analytics.ts
- src/vscripts/api/analytics/dto/game-end-dto.ts
- src/vscripts/modules/event/event-npc-spawned.ts
- src/vscripts/modules/event/game-end/game-end-point.test.ts
- src/vscripts/modules/event/game-end/game-end.ts
- src/vscripts/modules/hero/hero-facet-config.ts
- src/vscripts/modules/hero/hero-pick.ts
> Bot facet config and analytic 

- src/panorama/react/hud_lottery/components/KeyBindContainer.tsx
- src/panorama/react/hud_lottery/components/KeySettingButton.tsx
- src/panorama/react/hud_lottery/hotkey.ts
> keybind for passive

- game/resource/addon_english.txt
- game/resource/addon_schinese.txt
- src/common/events.d.ts
- src/panorama/react/hud_lottery/KeyBind.tsx
- src/panorama/react/hud_lottery/Lottery.tsx
- src/panorama/react/hud_lottery/components/KeyBindContainer.tsx
- src/panorama/react/hud_lottery/components/KeyBindRemember.tsx
- src/panorama/react/hud_lottery/components/KeySettingButton.tsx
- src/panorama/react/hud_lottery/components/LotteryContainer.tsx
- src/panorama/utils/net-table.ts
- src/vscripts/api/api-client.ts
- src/vscripts/api/player.ts
- src/vscripts/modules/hero/hero-facet-config.ts
> Save key bind

- src/vscripts/api/api-client.ts
- src/vscripts/api/player.ts
> Fix remember hotkey

- game/scripts/vscripts/abilities/ogre_magi_multicast_lua.lua
- src/panorama/react/hud_lottery/KeyBind.tsx
> Update KeyBind default not remember

- content/panorama/scripts/custom_game/game_mode.js
- game/scripts/npc/npc_abilities_override.txt
- game/scripts/vscripts/bot/bot_think_ability_use.lua
- src/common/events.d.ts
- src/common/net_tables.d.ts
- src/vscripts/api/api-client.ts
- src/vscripts/modules/GameConfig.ts
- src/vscripts/modules/event/event-game-state-change.ts
- src/vscripts/modules/event/game-end/game-end-point.test.ts
- src/vscripts/modules/event/game-end/game-end-point.ts
- src/vscripts/modules/event/game-end/game-end.ts
- src/vscripts/modules/option.ts
> Balance and bug fix

- game/resource/addon_english.txt
- game/resource/addon_russian.txt
> Fix russian translation UI

- game/resource/addon_english.txt
- game/resource/addon_russian.txt
- game/resource/addon_schinese.txt
- src/vscripts/api/api-client.ts
- src/vscripts/modules/option.ts
> Change text points to experience

- game/scripts/npc/neutral_items.txt
- game/scripts/npc/npc_items_override_neutral_passive.txt
- game/scripts/vscripts/bot/bot_think_item_build.lua
- game/scripts/vscripts/bot/bot_think_modifier.lua
- game/scripts/vscripts/items/item_necronomicon_staff.lua
- src/vscripts/ai/AI.ts
- src/vscripts/ai/action/action-ability.ts
- src/vscripts/ai/action/action-attack.ts
- src/vscripts/ai/hero/bot-base.ts
- src/vscripts/ai/hero/hero-base.ts
- src/vscripts/ai/hero/hero-drow-ranger.ts
- src/vscripts/ai/hero/hero-lion.ts
- src/vscripts/ai/hero/hero-luna.ts
- src/vscripts/ai/hero/hero-medusa.ts
- src/vscripts/ai/hero/hero-shadow-shaman.ts
- src/vscripts/ai/hero/hero-skeleton.ts
- src/vscripts/ai/hero/hero-sniper.ts
- src/vscripts/ai/hero/hero-viper.ts
- src/vscripts/ai/item/neutral-item.ts
- src/vscripts/ai/mode/FSA.ts
- src/vscripts/ai/mode/mode-attack.ts
- src/vscripts/ai/mode/mode-base.ts
- src/vscripts/ai/mode/mode-laning.ts
- src/vscripts/ai/mode/mode-push.ts
- src/vscripts/ai/mode/mode-retreat.ts
- src/vscripts/modules/GameConfig.ts
> Impl bot neutral item build

- game/scripts/npc/npc_items_override_neutral.txt
- src/vscripts/ai/item/neutral-item.ts
> Balance bot neutral items

- game/resource/addon_english.txt
- game/resource/addon_schinese.txt
- game/scripts/npc/npc_abilities_custom_new.txt
- game/scripts/npc/npc_abilities_override.txt
- src/vscripts/api/api-client.ts
- src/vscripts/modules/lottery/lottery-abilities.ts
- src/vscripts/utils/precache-data.ts
- src/vscripts/utils/precache.ts
> Add new draft abilitiy Defilement.

- content/panorama/scripts/custom_game/game_mode.js
- game/resource/addon_english.txt
- game/resource/addon_schinese.txt
- src/vscripts/ai/item/neutral-item.ts
- src/vscripts/modules/helper/bot-power.ts
> Nerf N4~N6 Bot multiplier

- game/scripts/npc/npc_abilities_override.txt
- src/vscripts/api/api-client.ts
> Try to fix api connection from China

- content/panorama/layout/custom_game/custom_loading_screen.xml
- src/vscripts/modules/GameConfig.ts
- src/vscripts/modules/hero/hero-facet-config.ts
> Fix bot facet select with 7.39

- content/panorama/layout/custom_game/custom_ui_manifest.xml
- content/panorama/layout/custom_game/end_screen_2.xml
- content/panorama/scripts/custom_game/end_screen_2.js
- game/resource/addon_english.txt
- game/resource/addon_schinese.txt
- game/scripts/custom_net_tables.txt
- game/scripts/npc/npc_abilities_creep.txt
- game/scripts/npc/npc_abilities_override.txt
- src/common/net_tables.d.ts
- src/vscripts/ai/AI.ts
- src/vscripts/api/game.ts
- src/vscripts/modifiers/global/fort_think.ts
- src/vscripts/modules/event/event-entity-killed.ts
- src/vscripts/modules/event/event-game-state-change.ts
- src/vscripts/modules/event/game-end/game-end.ts
> Fix abilities and game end

- content/panorama/scripts/custom_game/end_screen_2.js
- src/vscripts/modifiers/global/fort_think.ts
> Game end won't pause

- content/panorama/layout/custom_game/end_screen_2.xml
- content/panorama/scripts/custom_game/end_screen_2.js
- content/panorama/styles/custom_game/end_screen.css
- game/resource/addon_english.txt
- game/resource/addon_schinese.txt
- game/scripts/vscripts/events.lua
- src/common/net_tables.d.ts
- src/vscripts/modules/GameConfig.ts
- src/vscripts/modules/event/game-end/game-end.ts
> Ending screen add tower kills, neutral passive item

- game/scripts/vscripts/event/kill.lua
- game/scripts/vscripts/events.lua
- src/vscripts/modules/event/event-game-state-change.ts
> Refactor tower ability level setting

- content/panorama/scripts/custom_game/game_mode.js
- game/scripts/npc/npc_abilities_custom.txt
- game/scripts/npc/npc_abilities_custom_lottery.txt
- game/scripts/npc/npc_abilities_override.txt
- game/scripts/npc/npc_heroes_custom.txt
- game/scripts/npc/npc_items_artifact.txt
- src/scripts/launch.js
- src/vscripts/modules/lottery/lottery-abilities.ts
- src/vscripts/utils/precache.ts
> Hero balance

- game/scripts/npc/npc_abilities_override.txt
> Fix viper ability bug

- game/scripts/vscripts/bot/bot_item_data.lua
- game/scripts/vscripts/bot/bot_think_item_build.lua
- src/.cursor/rules/typescript-naming.mdc
- src/vscripts/ai/build-item/sell-item-config.ts
- src/vscripts/ai/build-item/sell-item.ts
- src/vscripts/ai/hero/bot-base.ts
> Bot sell duplicate items

- game/resource/addon_english.txt
- game/resource/addon_schinese.txt
- game/scripts/npc/npc_items_custom.txt
- game/scripts/vscripts/items/item_saint_orb.lua
> Revert saint orb

- game/resource/addon_english.txt
- game/resource/addon_schinese.txt
- game/scripts/npc/npc_items_custom.txt
- game/scripts/vscripts/items/item_saint_orb.lua
- src/vscripts/items/ts_items/item_saint_orb.ts
> Refactor sanit orb
